### ISSUE TITLE
Build install script

### ISSUE THREAD

**Issue by faddat** [universelabs/universe-blockchain#5]
**Description**
We need to build an installer.

**Tasks**
- [x] Create a mac installer

**Comment by faddat** [comment]
This issue won't be completed until 0.2, since 0.1 is all-mac

**Comment by faddat** [comment]
Finished; cloising

**Comment by guylepage3** [comment]
Adding reference tutorials here..

### Tutorials used:

https://blog.althea.net/making-a-cosmos-chain/

### Pertinent Tutorials:

https://cosmos-sdk.readthedocs.io/en/develop/staking/testnet.html
