### ISSUE TITLE
Make binaries directory hidden

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-blockchain#6]
**Description**
To prevent files from being deleted in their home directory, we will need to either do one of two things;

1. Allow the user to save the binaries to a directory of their choosing.
2. Save the binaries to a hidden directory in the user’s home directory called `.universe`.

CHOSEN in Slack: Option 2.

**Tasks**
- [x] Make binaries directory from install script hidden. New name `.universe`
- [x] Update CLI UI wording to reflect the change above.

**Comment by faddat** [comment]
It's complete now.

**Comment by guylepage3** [comment]
@faddat, based upon @vsund's recommendation from the Slack conversation below. I'd like us to implement `~/.universe/bin/` as it makes the most logical sense.

https://universelabs.slack.com/archives/CD22EAGUX/p1568574508092500?thread_ts=1568492068.032900&cid=CD22EAGUX
```
Jacob Gadikian Sep 14th at 4:14 PM
"that's just how it is"
.folders are for settings and the like

vsund  17 hours ago
i know a few exceptions for this :wink:  e.g. ~/.bin/, ~/.yarn/bin/ and ~/.local/bin/

vsund  17 hours ago
(sorry to bring this debate back up :D)

Guy Lepage  < 1 minute ago
@jacob I like this proposal from @vsund. Let’s implement this method.
```

**Comment by faddat** [comment]
finished; closing
